version: '3'
services:
  web:
    image: chimerast/niconico-speenya:develop
    environment:
      SERVER_URL: http://localhost:8080
    ports:
      - 8080:8080
    volumes:
      - ./data/:/app/data/
